<?php

return [
	['id' => '1', 'email' => 'gashe@sst.su', 'pass' => '31337', 'price_category' => '2', 'last_visit_tmstmp' => '1473861951', 'code_1c' => '1', 'name' => 'Гаше Родион Эдуардович Первый', 'fullname' => 'fullname', 'ou_category_id' => '1', 'has_credit' => '0', 'bonus' => '23983,2', 'credit' => '', 'region_id' => '19', 'balance' => '0', 'is_active' => '1', 'ip' => '192.168.75.33', 'num_visits' => '1', 'ip2' => null, 'allowed_paytypes' => '3', 'is_api_active' => '1'],
	['id' => '2', 'email' => '3@sst.su', 'pass' => '3333', 'price_category' => '2', 'last_visit_tmstmp' => '1536930054', 'code_1c' => '00694456', 'name' => 'name', 'fullname' => 'fullname', 'ou_category_id' => '3', 'has_credit' => '0', 'bonus' => null, 'credit' => '', 'region_id' => '19', 'balance' => '0', 'is_active' => '1', 'ip' => '127.0.0.1', 'num_visits' => '3', 'ip2' => '192.168.75.77', 'allowed_paytypes' => '3', 'is_api_active' => '1'],
	['id' => '3', 'email' => '2@sst.su', 'pass' => '2222', 'price_category' => '2', 'last_visit_tmstmp' => '1573459678', 'code_1c' => '8531314', 'name' => 'name', 'fullname' => 'fullname', 'ou_category_id' => '2', 'has_credit' => '0', 'bonus' => '23983,2', 'credit' => '200000.0 руб.', 'region_id' => '19', 'balance' => '0', 'is_active' => '1', 'ip' => '127.0.0.1', 'num_visits' => '113', 'ip2' => '10.10.10.1', 'allowed_paytypes' => '3', 'is_api_active' => '1'],
	['id' => '4', 'email' => 'mkazaryan@sst.su', 'pass' => 'mk2017ss', 'price_category' => '2', 'last_visit_tmstmp' => '1484665833', 'code_1c' => '8531314', 'name' => 'Казарян Михаил (МСК-К1)', 'fullname' => 'Казарян Михаил (МСК-К1)', 'ou_category_id' => '1', 'has_credit' => '1', 'bonus' => null, 'credit' => '200000.0 руб.', 'region_id' => '19', 'balance' => '0', 'is_active' => '1', 'ip' => '192.168.75.77', 'num_visits' => '2', 'ip2' => '192.168.75.124', 'allowed_paytypes' => '3', 'is_api_active' => '1'],
	['id' => '8', 'email' => '8598595@sst.su', 'pass' => '112534', 'price_category' => '2', 'last_visit_tmstmp' => '0', 'code_1c' => '8598595', 'name' => 'Рени РН - Рязань', 'fullname' => 'Рени РН - Рязань', 'ou_category_id' => '1', 'has_credit' => '0', 'bonus' => null, 'credit' => null, 'region_id' => '19', 'balance' => null, 'is_active' => '1', 'ip' => null, 'num_visits' => '0', 'ip2' => null, 'allowed_paytypes' => '3', 'is_api_active' => '1'],
	['id' => '9', 'email' => '8700946@sst.su', 'pass' => '112534', 'price_category' => '2', 'last_visit_tmstmp' => '1484665974', 'code_1c' => '8700946', 'name' => 'Питер  ООО «Рени СПБ»', 'fullname' => 'Питер  ООО «Рени СПБ»', 'ou_category_id' => '4', 'has_credit' => '0', 'bonus' => null, 'credit' => '', 'region_id' => '19', 'balance' => '115089751.76', 'is_active' => '1', 'ip' => '192.168.75.77', 'num_visits' => '1', 'ip2' => null, 'allowed_paytypes' => '3', 'is_api_active' => '1'],
	['id' => '10', 'email' => '8606276@sst.su', 'pass' => '112534', 'price_category' => '2', 'last_visit_tmstmp' => '0', 'code_1c' => '8606276', 'name' => 'Саратов  ООО "Рени СВ"', 'fullname' => 'Саратов  ООО "Рени СВ"', 'ou_category_id' => '1', 'has_credit' => '0', 'bonus' => null, 'credit' => null, 'region_id' => '19', 'balance' => null, 'is_active' => '1', 'ip' => null, 'num_visits' => '0', 'ip2' => null, 'allowed_paytypes' => '3', 'is_api_active' => '1'],
	['id' => '12', 'email' => 'peresypkin@groster-tire.ru', 'pass' => '1252478', 'price_category' => '2', 'last_visit_tmstmp' => '0', 'code_1c' => '08735770', 'name' => 'Гростэр', 'fullname' => 'ООО Гростэр', 'ou_category_id' => '2', 'has_credit' => '0', 'bonus' => null, 'credit' => null, 'region_id' => '19', 'balance' => null, 'is_active' => '1', 'ip' => null, 'num_visits' => '0', 'ip2' => null, 'allowed_paytypes' => '3', 'is_api_active' => '0'],
	['id' => '13', 'email' => 'kyazimov78@mail.ru', 'pass' => '233451', 'price_category' => '2', 'last_visit_tmstmp' => '0', 'code_1c' => '694432', 'name' => 'Кязимов Олег Николаевич', 'fullname' => 'Кязимов Олег Николаевич', 'ou_category_id' => '2', 'has_credit' => '0', 'bonus' => null, 'credit' => null, 'region_id' => '19', 'balance' => null, 'is_active' => '1', 'ip' => null, 'num_visits' => '0', 'ip2' => null, 'allowed_paytypes' => '3', 'is_api_active' => '0'],
	['id' => '15', 'email' => 'shinaonline@mail.ru', 'pass' => '86017', 'price_category' => '2', 'last_visit_tmstmp' => '0', 'code_1c' => 'БЛОК/88974932', 'name' => 'ШИНАШОП', 'fullname' => 'ШИНАШОП', 'ou_category_id' => '2', 'has_credit' => '1', 'bonus' => null, 'credit' => '56 376 руб.', 'region_id' => '19', 'balance' => null, 'is_active' => '1', 'ip' => null, 'num_visits' => '0', 'ip2' => null, 'allowed_paytypes' => '3', 'is_api_active' => '0'],
];
